version: "3"
services:

  test_bank_mysql_container:
    container_name: test_bank_mysql_container
    image: mysql:8.0
    ports:
      - ${TEST_BANK_MYSQL_BINDING_PORT}:3306
    volumes:
      - ${TEST_BANK_MYSQL_DATA_PATH}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${TEST_BANK_MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped

  test_bank_dev_redis_container:
    container_name: test_bank_redis_container
    image: redis:6.2.6-alpine
    ports:
      - ${TEST_BANK_REDIS_BINDING_PORT}:6379
    restart: unless-stopped

  test_bank_dev_mongodb_container:
    container_name: test_bank_mongodb_container
    image: mongo
    ports:
      - ${TEST_BANK_MONGODB_BINDING_PORT}:27017
    volumes:
      - ${TEST_BANK_MONGODB_DATA_PATH}:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${TEST_BANK_MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${TEST_BANK_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${TEST_BANK_MONGODB_PASSWORD}
    restart: unless-stopped
