spring:
  data:
    redis:
      host: localhost
      port: ${TEST_TRIP_REDIS_BINDING_PORT}
    mongodb:
      uri: mongodb://${TEST_TRIP_MONGODB_USERNAME}:${TEST_TRIP_MONGODB_PASSWORD}@localhost:${TEST_TRIP_MONGODB_BINDING_PORT}/?authSource=admin
      database: ${TEST_TRIP_MONGODB_DATABASE}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${TEST_TRIP_MYSQL_BINDING_PORT}/${TEST_TRIP_MYSQL_DATABASE}
    username: ${MYSQL_ROOT_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    servlet:
      path: /api
jwt:
  secret: ${JWT_SECRET_KEY}
